# Generated by Django 6.0.4 on 2026-04-08 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('video', 'Video'), ('project', 'Project')], max_length=10)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('item_type', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ThumbsUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ratable_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs_ups', to='ratings.ratableitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
