# Generated by Django 6.0.4 on 2026-04-08 05:02

import django.core.validators
import django.db.models.deletion
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('friends', 'Friends'), ('employers', 'Potential Employers'), ('visitors', 'Regular Visitors')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PasswordUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='images.accesspassword')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=images.models.portfolio_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'tiff'])])),
                ('date_taken', models.DateField()),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('camera_used', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('friends', 'Friends'), ('employers', 'Potential Employers'), ('visitors', 'Regular Visitors')], default='visitors', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_lossless', models.BooleanField(default=True, help_text='Image stored in lossless format')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='portfolio_images', to='images.tag')),
            ],
            options={
                'ordering': ['order', '-date_taken'],
                'indexes': [models.Index(fields=['category'], name='images_port_categor_29d2bd_idx'), models.Index(fields=['date_taken'], name='images_port_date_ta_8eed68_idx')],
            },
        ),
    ]
